### PR TITLE
Add `natural_arch` icon

### PR DESCRIPTION
**Pull request by jake-low**
Add an icon for natural rock arches (OSM's [`natural=arch`](https://wiki.openstreetmap.org/wiki/Tag:natural%3Darch)). The appearance is modeled after Utah's [Delicate Arch](https://en.wikipedia.org/wiki/Delicate_Arch).

Here's what the icon looks like at the 40px and 15px sizes:

image

### CODE REVIEW

**Comment by bhousel** [comment]
Hey @jake-low thanks!  that looks great 👍

**Comment by bhousel** [comment]
Btw, do you want me to make a temaki release for this, or do you want me to hold off for now if you are planning to add some more icons?

**Comment by jake-low** [comment]
A release would be great if you have the time! I'm not planning to add any more icons right now but I'm hoping to add a preset to openstreetmap/id-tagging-schema that uses this icon.

**Comment by bhousel** [comment]
No trouble at all, I just published [v5.10.0](https://github.com/rapideditor/temaki/releases/tag/v5.10.0)

**Pull request merged**
