### PR TITLE
add icon for curbs of unspecified type

### PR DESCRIPTION
**Pull request by tyrasd**
This would be for https://github.com/openstreetmap/id-tagging-schema/pull/1077

I chose the raised curb icon as the base for this, because I'd assume that that's the fallback most data consumers would choose, if the type of curb is nor mapped (it's probably safer to route a wheelchair user a longer route compared to getting them stuck at an unspecified curb).  //edit: icon slightly updated after feedback in comment below)

As an alternative I had also played around with using stripes to indicate the unknown height of the curb, like this:  Let me know if you'd prefer that one.

### CODE REVIEW

**Comment by tordans** [comment]
In general I agree that a different icon would be great in this case.

A few thoughts on the "iconography"…

I wonder if it is a good idea to add symbols like the question mark as element to indicate unspecified elements … because if we start with that, it would ideally span to other cases as well. What other cases are there? 
- We have the unspecified trees. In https://github.com/rapideditor/temaki/issues/87#issuecomment-1771661215 Bryan suggested a question mark solution as well
- …

The second option would be more in line with what we have (AKA we don't use "letters" ATM), however I don't think its easy enough to understand out of context.

The `?` in your version looks a bit too thing. I wonder if the `(?)` from Bryans Example in https://github.com/rapideditor/temaki/issues/87#issuecomment-1771661215 would be a better fit instead?

**Comment by tyrasd** [comment]
Yeah… I was also not 100% happy with the question mark in the icon, that's why I played around with the shaded version. But I wasn't really happy with that one as well (for the reasons you identified).

I'm not a trained designer, so take this with a grain (or two) of salt:
Interestingly, the question mark seems to be an (arguably) [almost](https://linguistics.stackexchange.com/a/12881) "universally recognized" symbol. Only very few languages/scripts use different symbols for it (Greek is one example). At least compared to a few other symbols we use in the icon sets (e.g. the `$` in [`car_dealer.svg`](https://github.com/rapideditor/temaki/blob/558398/icons/car_dealer.svg)), this one seems to be fine to represent a situation of _unspecific state_ and/or the _lack of knowledge_ of the mapper creating these objects.

For presets, I would recommend to only use a `?` icon for very specific cases, e.g., if there is a "generic" preset for which an exhaustive list of specialized subpresets exists which can be considered to be preferable to be mapped.

**Comment by tyrasd** [comment]
> The ? in your version looks a bit too thin

I don't know which font was used for the mockup in the tree issue… But this might be better:  (for comparison here it is next to the original one from this PR:  ).

**Comment by tyrasd** [comment]
> What other cases are there?

The (hidden) presets for `shop=yes`, `man_made=yes`, `traffic_calming=yes`, etc. would be candidates to make them visually stand out on the map. Maybe also something like the `amenity/parking` preset.

**Comment by bhousel** [comment]
Without adding a better tag, iD just shows a dot.  Isn't this ok?
I've always considered the dot as "some tag is here but it's not recognized".
This is the kind of signal we want to give the user to pick something better.

Screenshot 2024-02-28 at 9 04 10 AM

**Comment by tyrasd** [comment]
This icon would be for [`barrier=kerb`](https://github.com/openstreetmap/id-tagging-schema/blob/main/data/presets/barrier/kerb.json), which is currently using `temaki-kerb-raised` as an icon, which is not ideal as it is doubling as the icon for the Raised Curb preset for which it was designed. Completely dropping the icon from the generic Curb preset would be an option, but in my opinion not the greatest.

**Pull request merged**
