### PR TITLE
Create fire_hydrant_underground.svg

### PR DESCRIPTION
**Pull request by qugebert**
I combined the existing icons from gas_manhole.svg and hydrant.svg and made it oval.

### CODE REVIEW

**Comment by bhousel** [comment]
Thanks!
Is this related to some other issue somewhere?
Also, why did you make it oval?

**Comment by qugebert** [comment]
There has been the suggestion to make a seperate preset for underfloor hydrants to avoid confusion (pillar icon might be confusing for underfloor hydrants), somewhere here: https://github.com/streetcomplete/StreetComplete/pull/5373#issuecomment-1864784864

It is oval, because all underfloor hydrant manholes i've ever seen are oval. 
See for example https://wiki.openstreetmap.org/wiki/File:Berlin_hydrant_20050211_p1000517.jpg
and the actual pillar is mounted by firefighters if needed:
https://wiki.openstreetmap.org/wiki/File:Standrohr_unterflurhydrant.jpg
And in editors where the icons are quite small, the oval form might help to distinguish it as fire hydrant manhole.

But i didn't think that they might look different in other countries, sorry.

**Comment by qugebert** [comment]
Ok, i tried how it would look in id-editor, the small icons are too small in all cases, but i think the round is a bit better.
grafik 
grafik

**Comment by bhousel** [comment]
Thanks, yeah I agree that the round one looks a little better.  At that small size it's really hard to see the details in either case, but I mostly think it would be weird for this icon to be a different shape from all the other ones.

**Pull request merged**
